version: '3.8'

services:
  scrumptious_postgres:
    image: postgres
    container_name: scrumptious_postgres
    restart: always
    ports:
      - '5432:5432'
      - '127.0.0.1:8888:5432'
    env_file:
      - postgres.env
    volumes:
      - scrumptious_postgres:/var/lib/postgresql/data

volumes:
  scrumptious_postgres:
    driver: local
